server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/pinchfood
spring.data.mongodb.database=pinchfood

# minio.url=http://127.0.0.1:9000
# minio.access-key=minioadmin
# minio.secret-key=minioadmin
# minio.bucketname=foodpinch

cloudinary.cloud_name=dejmf2pbw
cloudinary.api_key=875723913159655
cloudinary.api_secret=675unFDe01EgriB2qSZmxHmYAyM

# JWT CONFIG
jwt.secret=4F1C2A998B7E4FA29DAB99F23B77CC11
jwt.expiration=3600000
